/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;



import java.io.*;
import com.google.gson.Gson;




public class App {

    public static void main(String[] args) {

            String path ="C:\\Users\\user\\Desktop\\code401\\quotes\\app\\src\\main\\resources\\quotes.json";
            getQuote(path);

    }



    public static void getQuote(String path){
        // create Gson instance
        Gson gson = new Gson();
        FileReader fileReader = null;
        try {
            // create a reader
            fileReader = new FileReader(path);
            Quotes[] quotes = gson.fromJson(fileReader, Quotes[].class);
            int randomQuote = (int)(Math.random() * quotes.length);
            System.out.println(quotes[randomQuote]);


            // close reader
            fileReader.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }





}
